### PR TITLE
Add Avahi to Dockerfile (Chromecast Support from within Docker)

### PR DESCRIPTION
**Pull request by dersimn**
Build and try with:

    docker build -t dashkiosk:dev1 .
    docker run --net=host -e "chromecast__enabled=1" -e "chromecast__receiver=http://10.30.21.20:8081/receiver" -e "port=8081" dashkiosk:dev1

### CODE REVIEW

**Comment by dersimn** [comment]
Try this, I'm quite new to the workflows around here ;)

**Comment by vincentbernat** [comment]
I don't know if there are many users of this, but since the entrypoint is changing, users now have to provide the node command to pass arguments while this was not needed before. Before:

```
docker run dashkiosk --arg1 --arg2
```

After:

```
docker run dashkiosk node /dashkiosk/server.js --arg1 --arg2
```

I don't know what pattern is the most common, but to avoid breaking people setup, I think entrypoint should also include call to node or the wrapper script should invoke node. Unless there is a good reason not too.

**Comment by dersimn** [comment]
Good point, I'll look into that, but that would be difficult to achieve.  
I would suggest to use a different tag on Docker Hub anyway - `dashkiosk:latest` and `dashkiosk:chromecast` for e.g.

**Comment by vincentbernat** [comment]
Thanks!

**Pull request merged**
